### ISSUE TITLE
Source files are deleted when hardlinks can't be created

### ISSUE THREAD

**Issue by sbraz** [pauldreik/rdfind#5]
When running the script on multiple devices, the following error appears:
```
failed to make hardlink /mount1/…/file1 to /mount2/…/file2    
Rdutil.cc: Failed to apply function f on it. 
```
`file1` ends up being deleted. There should be some kind of check to verify that both files live in the same device.
I'm running 1.3.5, I haven't checked the git master.

**Comment by pauldreik** [comment]
This is indeed bad, and I will try to fix it. Thanks!

**Comment by pauldreik** [comment]
I made an initial fix. A unit test to provoke the error, and then a quick fix that seems to work.
The randomness helper class should move elsewhere and have it's interface polished a bit, but could you perhaps give it a try? (on non-critical data, please :-)
7e899307ed08099e3444ad689c5b61d846d5483b

**Comment by sbraz** [comment]
I've tried and it works. The random part makes it fail if a file is too long though. Maybe you could catch `ENAMETOOLONG` and try something else in this case?
```
rename("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaxallbyqxjylgafqe") = -1 ENAMETOOLONG (File name too long)
```

**Comment by pauldreik** [comment]
The same problem applied to making symlinks, so I fixed that too.
Regarding the overly long filenames, the random temporary filename is now replacing the original filename, not appended to it. The length should now only be exceeded for files with names shorter than the length of the random name (set to 16 chars, approximately 96 bits of randomness). Any failure of renaming/unlinking/hardlinking/symlinking is reported, and if possible the original file is moved back so it does not vanish.
While fixing the symlinks, I removed some cruft from the code. Tests have been added.
This will be part of the next release.

**Comment by pauldreik** [comment]
I just tagged the first release candidate for 1.4.0. @sbraz would you mind checking that you are happy with the handling and message? See below or try for yourself!

> ./rdfind -makehardlinks true -removeidentinode false /bin/ls /bin/ls
Now scanning "/bin/ls", found 1 files.
Now scanning "/bin/ls", found 1 files.
Now have 2 files in total.
Total size is 267584 bytes or 261 KiB
Removed 0 files due to unique sizes from list.2 files left.
Now eliminating candidates based on first bytes:removed 0 files from list.2 files left.
Now eliminating candidates based on last bytes:removed 0 files from list.2 files left.
Now eliminating candidates based on sha1 checksum:removed 0 files from list.2 files left.
It seems like you have 2 files that are not unique
Totally, 131 KiB can be reduced.
Now making results file results.txt
Now making hard links.
Failed moving file /bin//ls to a temporary
Making 0 links.


> ./rdfind -makesymlinks true -removeidentinode false /bin/ls /bin/ls
Now scanning "/bin/ls", found 1 files.
Now scanning "/bin/ls", found 1 files.
Now have 2 files in total.
Total size is 267584 bytes or 261 KiB
Removed 0 files due to unique sizes from list.2 files left.
Now eliminating candidates based on first bytes:removed 0 files from list.2 files left.
Now eliminating candidates based on last bytes:removed 0 files from list.2 files left.
Now eliminating candidates based on sha1 checksum:removed 0 files from list.2 files left.
It seems like you have 2 files that are not unique
Totally, 131 KiB can be reduced.
Now making results file results.txt
Now making symbolic links. creating 
Failed moving file /bin//ls to a temporary
Failed to make symlink /bin//ls to /bin//ls
Making 0 links.

**Comment by sbraz** [comment]
> `to a temporary`

Is that supposed to be `to a temporary file`?

Other than that, everything seems to work fine.

**Comment by pauldreik** [comment]
Thanks, fixed!
